### ISSUE TITLE
reconstruct-lineage error: IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by isshamie** [YosefLab/Cassiopeia#118]
Hello I'm trying to run reconstruct_lineages.ipynb but with the test data data/test_at.txt as the allele table. It seemed to output the allele table fine  but when I ran reconstruct lineage I got an error. I am wondering what is the exact input format for the reconstruct-lineage section? Right now the test_lg4_character_matrix.txt I have is below (just first 3 lines). Below that is the error I encountered. Thank you.
```
cellBC	r0	r1	r2	r3	r4	r5	r6	r7	r8	r9	r10	r11	r12	r13	r14	r15	r16	r17	r18	r19	r20	r21r22	r23	r24	r25	r26	r27	r28	r29	r30	r31	r32	r33	r34	r35	r36	r37	r38	r39	r40	r41	r42	r43	r44	r45	r46	r47	r48	r49	r50

IVLT-2B_00.AAACCTGGTCTGGTCG-1	0	0	0	2	2	0	2	0	0	0	2	2	0	2	0	0	0	0	2	20	0	2	2	0	2	0	2	0	0	0	2	0	0	0	0	2	0	0	-	-	-	-	--	-	-	-	-	-	-  
IVLT-2B_00.AAACCTGTCCACTCCA-1	0	0	0	2	0	0	2	0	2	-	-	-	0	2	0	2	0	0	2	20	0	2	2	2	0	0	2	0	2	-	-	-	2	2	0	0	2	2	0	0	0	-	--	-	-	-	-	-	-  
```

The command and error message
```
reconstruct-lineage test_lg4_character_matrix.txt test_lg4_tree.pkl --hybrid
running algorithm...
Using 1 threads, 48 available.
Sending off Target Sets: 1
Started new thread for: 0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0 (num targets = 10) , pid = ea70d39f9eb88a0a5b0739128f47b4d5
(2, 51)
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 421, in wrapped
    return func(*args, **kwargs)
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 445, in prune_unique_alleles
    counts,
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 443, in <lambda>
    if len(np.where(x[1] == 1)) > 0
IndexError: index 2 is out of bounds for axis 0 with size 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 421, in wrapped
    return func(*args, **kwargs)
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 572, in find_good_gurobi_subgraph
    proot, targets_pruned, pruned_to_orig = prune_unique_alleles(root, targets)
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 423, in wrapped
    traceback_str = traceback.format_exc(e)
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'IndexError' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 423, in wrapped
    traceback_str = traceback.format_exc(e)
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 498, in __init__
    _seen=_seen)
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'TypeError' and 'int'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/isshamie/software/anaconda3/envs/cass/bin/reconstruct-lineage", line 33, in <module>
    sys.exit(load_entry_point('cassiopeia-lineage', 'console_scripts', 'reconstruct-lineage')())
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/reconstruct_tree.py", line 245, in main
    lookahead_depth=lookahead_depth,
  File "/home/isshamie/software/Cassiopeia/cassiopeia/TreeSolver/lineage_solver/lineage_solver.py", line 228, in solve_lineage_instance
    results, r, pid, graph_sizes = future.result()
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/data/isshamie/software/anaconda3/envs/cass/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: '>=' not supported between instances of 'TypeError' and 'int'
```

**Comment by mattjones315** [comment]
Hi @isshamie,

I'm not sure why this is erroring but it is likely because the example matrix is so small. If you are interested in using Cassiopeia for your research, please check out our `refactor` branch -- we have updated all of our code to make it much more user friendly. All of our documentation, including example notebooks, can be found [here](https://cassiopeia-lineage.readthedocs.io/en/testdeployment/).

**Comment by isshamie** [comment]
Thank you! That link and the dataset there did run.

**Comment by mattjones315** [comment]
Hi @isshamie,

I wanted to follow up and let you know that we have just set a new release (Cassiopeia 2.0.0) and made this publicly available from the `master` branch. We have updated all documentation and notebooks which can be found [here](https://cassiopeia-lineage.readthedocs.io/en/latest/index.html). 

Please do let us know if you have any future issues!

**Comment by isshamie** [comment]
Hi,
I used the new link you sent and for the most part it worked! However, there were two errors I encountered, one of which I made a workaround. In the first, when using the hybrid solver, the log file name became too long for my unix os b/c I had many variants (~230). I created random hash for those for now, and that worked.
In the 2nd case, the ILP solver gives me an error when I try to use -1 as missing values.  Without missing values, it worked fine. I also checked for duplicate cell entries. See below:
``` if priors is not None:
    ilp_solver = cas.solver.ILPSolver(convergence_time_limit=500, maximum_potential_graph_layer_size=500, weighted=True, seed=1234)
else:
    ilp_solver = cas.solver.ILPSolver(convergence_time_limit=500, maximum_potential_graph_layer_size=500, weighted=False, seed=1234)
ilp_solver.solve(cas_tree)
 ```


```[2021-08-10 01:43:13,323]    INFO [ILPSolver] Solving tree with the following parameters.
[2021-08-10 01:43:13,324]    INFO [ILPSolver] Convergence time limit: 500
[2021-08-10 01:43:13,325]    INFO [ILPSolver] Convergence iteration limit: 0
[2021-08-10 01:43:13,326]    INFO [ILPSolver] Max potential graph layer size: 500
[2021-08-10 01:43:13,327]    INFO [ILPSolver] Max potential graph lca distance: None
[2021-08-10 01:43:13,328]    INFO [ILPSolver] MIP gap: 0.01
[2021-08-10 01:43:15,214]    INFO [ILPSolver] (Process: fcea3401d501dbbb34fe30d0470cec91) Estimating a potential graph with a maximum layer size of 500 and a maximum LCA distance of 63.
[2021-08-10 01:43:18,159]    INFO [ILPSolver] (Process: fcea3401d501dbbb34fe30d0470cec91) Maximum layer size exceeded, returning network.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-da8d2ee52914> in <module>
      3 else:
      4     ilp_solver = cas.solver.ILPSolver(convergence_time_limit=500, maximum_potential_graph_layer_size=500, weighted=False, seed=1234)
----> 5 ilp_solver.solve(cas_tree)

/data/isshamie/software/anaconda3/envs/mito_trace/lib/python3.6/site-packages/ngs_tools/logging.py in inner(*args, **kwargs)
     60                 try:
     61                     self.namespace = namespace
---> 62                     return func(*args, **kwargs)
     63                 finally:
     64                     self.namespace = previous

/data/isshamie/software/anaconda3/envs/mito_trace/lib/python3.6/site-packages/cassiopeia/solver/ILPSolver.py in solve(self, cassiopeia_tree, layer, collapse_mutationless_edges, logfile)
    220         _potential_graph = nx.relabel_nodes(potential_graph, encoder)
    221         #print('targets', targets)
--> 222         _targets = list(map(lambda x: encoder[x], targets))
    223         _root = encoder[root]
    224 

/data/isshamie/software/anaconda3/envs/mito_trace/lib/python3.6/site-packages/cassiopeia/solver/ILPSolver.py in <lambda>(x)
    220         _potential_graph = nx.relabel_nodes(potential_graph, encoder)
    221         #print('targets', targets)
--> 222         _targets = list(map(lambda x: encoder[x], targets))
    223         _root = encoder[root]
    224 

KeyError: (-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, 1, -1, -1, 0, 1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, 0, 1, -1, -1, -1, -1, -1, -1, 0, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, 0, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
```

P.S. I was not sure to open a new issue for this or not.

**Comment by mattjones315** [comment]
Hi @isshamie ,

Thanks for posting this issue, and apologies for not responding to this earlier this week. Judging by the log output, I believe the reason why this is happening is because the `ILPSolver` cannot solve for even the first layer of the potential graph. We hadn't anticipated this issue because most of our datasets are not this complex (as measured by the # of target sites and missing data).

You can likely circumvent this issue by increasing the parameter `maximum_potential_graph_layer_size ` -- I see you're using 500, and apologies if this was not clear in the tutorial, but this is just for the small example dataset. We normally use 10,000 as our `maximum_potential_graph_layer_size`. Try this out and let me know if it works.

On our end, we'll try and throw a more specific error if another user encounters this problem.

Hope this helps!

**Comment by mattjones315** [comment]
Hi @isshamie ,

Can you please confirm that this solves your problem? Or if not, could you let us know what else we can help with?

Thanks in advance!

**Comment by mattjones315** [comment]
Hi @isshamie ,

Since we haven't heard from you on this issue and the previous PR #140 seems to have addressed this error, I'm going to go ahead and close this. Feel free to re-open this issue or open another one if you run into more trouble.

Thanks!

-Matt
