### ISSUE TITLE
Error in resolve_umi_sequence

### ISSUE THREAD

**Issue by cnk113** [YosefLab/Cassiopeia#174]
Hello,

I was following the tutorial for the preprocessing, and when I get to the resolve_umi_sequence I get an error thrown. 
`__init__() got an unexpected keyword argument 'basey'`
I believe it's a deprecation of the params in the new matplotlib version.

Best,
Chang

**Comment by mattjones315** [comment]
Hi @cnk113 ,

Thanks for bringing this to our attention - we'll mark this as a bug and fix this as soon as we can.

Thanks,
Matt

**Comment by zebrafishCC** [comment]
I had the issues as @cnk113  mentioned.

**Comment by zebrafishCC** [comment]
I had the same issue as @cnk113 mentioned

**Comment by lamyankin** [comment]
@mattjones315 Hi, I met the same error, have you fix the bug?

**Comment by mattjones315** [comment]
Sorry for the very long delay here folks (over a year!). This has been fixed with the latest PR #189. You might have already gotten around this issue by downgrading matplotlib, but this new PR fixes the issue.

Thanks for your patience and please let me know if you have any other issues!

**Comment by lamyankin** [comment]
Thank you for your reply and fix the bug, I have recloned the Cassiopeia and rerun the pipline from the step of  [resolve] with the input file /test.collapse.txt (9GB). However, I just got a 27KB output file /test.resolve.txt and met a error. Here is my .cfg file, and the process.

![image](https://user-images.githubusercontent.com/86952016/223714097-0055f5e2-5ff3-4677-8d56-6fc3b4084b24.png)
![image](https://user-images.githubusercontent.com/86952016/223714192-852f4c2f-0db6-42b3-8379-3567463e7316.png)

(py39) zwf 19:42:35 ~/Cassiopeia/Cassiopeia
$ cassiopeia-preprocess /home/zwf/Cassiopeia/Cassiopeia/data/preprocess.cfg
[2023-03-08 19:42:49,122]    INFO [main] Starting...
[2023-03-08 19:44:16,381]   DEBUG [resolve] Keyword arguments: {'min_avg_reads_per_umi': 2.0, 'min_umi_per_cell': 10, 'plot': True, 'output_directory': '/home/zwf/Cassiopeia'}
[2023-03-08 19:44:16,381]    INFO [resolve] Starting...
Resolving UMI sequences: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9192538/9192538 [19:54<00:00, 7695.42it/s]
[2023-03-08 20:05:18,606]    INFO [resolve] Filtered out 6148434 reads.
/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/shape_base.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ary = asanyarray(ary)
[2023-03-08 20:07:14,583]    INFO [resolve] Filtered out 136739 cells with too few UMIs or too few average number of reads per UMI.
[2023-03-08 20:07:17,432]    INFO [resolve] Filtered out 9192495 UMIs as a result.
[2023-03-08 20:07:17,765]   DEBUG [resolve] Resulting molecule_table statistics:
[2023-03-08 20:07:17,765]   DEBUG [resolve] # Reads: 86
[2023-03-08 20:07:17,765]   DEBUG [resolve] # UMIs: 43
[2023-03-08 20:07:17,765]   DEBUG [resolve] # Cell BCs: 3
[2023-03-08 20:07:20,273]    INFO [resolve] Finished in 1383.8925580978394 s.
[2023-03-08 20:07:22,174]   DEBUG [align] Keyword arguments: {'gap_open_penalty': 20, 'gap_extend_penalty': 1, 'method': 'local', 'ref_filepath': '/home/zwf/Cassiopeia/Cassiopeia/data/PCT48.ref.fasta', 'ref': None, 'n_threads': 32}
[2023-03-08 20:07:22,174]    INFO [align] Starting...
Aligning sequences to reference: 100%|#####################################################################################################################################################################| 43/43 [00:06<00:00,  6.76it/s]
[2023-03-08 20:07:28,551]    INFO [align] Finished in 6.377103805541992 s.
[2023-03-08 20:07:28,552]   DEBUG [call_alleles] Keyword arguments: {'barcode_interval': (20, 34), 'cutsite_locations': [112, 166, 220], 'cutsite_width': 12, 'context': True, 'context_size': 5, 'ref_filepath': '/home/zwf/Cassiopeia/Cassiopeia/data/PCT48.ref.fasta', 'ref': None}
[2023-03-08 20:07:28,553]    INFO [call_alleles] Starting...
Parsing CIGAR strings into indels: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 10443.26it/s]
/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/pipeline.py:641: PreprocessWarning: Detected missing data in alleles. You might consider re-running align_sequences with a lower gap-open penalty, or using a separate alignment strategy.
  warnings.warn(
[2023-03-08 20:07:28,562]    INFO [call_alleles] Finished in 0.009550809860229492 s.
[2023-03-08 20:07:28,563]   DEBUG [error_correct_intbcs_to_whitelist] Keyword arguments: {'intbc_dist_thresh': 1, 'whitelist': ['ATGATTTAACTACT', 'CGATTGGTCACTTA', 'CGTGAGTCTCTGAT', 'GAACCCACAATTCC', 'GAGTATATACCCTT', 'GCGTTTAGAATATT', 'GCCTTCAATTCCAA', 'TAACCAAGCCTACA', 'TTTCGTCGCTCTTC', 'CGCTATGGGGGGAA', 'CGATATCTTCAAGC', 'TCAGTGGGGTATTG', 'ACAATGCGTGTGGC']}
[2023-03-08 20:07:28,563]    INFO [error_correct_intbcs_to_whitelist] Starting...
[2023-03-08 20:07:28,563]    INFO [error_correct_intbcs_to_whitelist] 1 intBCs detected.
Correcting intBCs to whitelist: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11214.72it/s]
[2023-03-08 20:07:28,565]    INFO [error_correct_intbcs_to_whitelist] Finished in 0.0015685558319091797 s.
[2023-03-08 20:07:28,565]   DEBUG [error_correct_umis] Keyword arguments: {'max_umi_distance': 2, 'allow_allele_conflicts': False, 'n_threads': 32}
[2023-03-08 20:07:28,565]    INFO [error_correct_umis] Starting...
Error-correcting UMIs: 0it [00:00, ?it/s]
[2023-03-08 20:07:28,569]    INFO [error_correct_umis] Finished in 0.0042383670806884766 s.
[2023-03-08 20:07:28,569]    INFO [main] Finished in 1479.447678565979 s.
Traceback (most recent call last):
  File "/home/pci/miniconda3/envs/py39/bin/cassiopeia-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 64, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/cassiopeia_preprocess.py", line 125, in main
    data = procedure(data, **pipeline_parameters[stage])
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 86, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 64, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/pipeline.py", line 786, in error_correct_umis
    alignment_df = pd.concat(alignment_dfs, sort=True)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
 

> Sorry for the very long delay here folks (over a year!). This has been fixed with the latest PR #189. You might have already gotten around this issue by downgrading matplotlib, but this new PR fixes the issue.
> 
> Thanks for your patience and please let me know if you have any other issues!

Thank you for your reply and fix the bug, I have recloned the Cassiopeia and rerun the pipline from the step of  [resolve] with the input file /test.collapse.txt (9GB). However, I just got a 27KB output file /test.resolve.txt and met a error. Here is my .cfg file, and the process.

![image](https://user-images.githubusercontent.com/86952016/223714097-0055f5e2-5ff3-4677-8d56-6fc3b4084b24.png)
![image](https://user-images.githubusercontent.com/86952016/223714192-852f4c2f-0db6-42b3-8379-3567463e7316.png)

(py39) zwf 19:42:35 ~/Cassiopeia/Cassiopeia
$ cassiopeia-preprocess /home/zwf/Cassiopeia/Cassiopeia/data/preprocess.cfg
[2023-03-08 19:42:49,122]    INFO [main] Starting...
[2023-03-08 19:44:16,381]   DEBUG [resolve] Keyword arguments: {'min_avg_reads_per_umi': 2.0, 'min_umi_per_cell': 10, 'plot': True, 'output_directory': '/home/zwf/Cassiopeia'}
[2023-03-08 19:44:16,381]    INFO [resolve] Starting...
Resolving UMI sequences: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9192538/9192538 [19:54<00:00, 7695.42it/s]
[2023-03-08 20:05:18,606]    INFO [resolve] Filtered out 6148434 reads.
/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/shape_base.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ary = asanyarray(ary)
[2023-03-08 20:07:14,583]    INFO [resolve] Filtered out 136739 cells with too few UMIs or too few average number of reads per UMI.
[2023-03-08 20:07:17,432]    INFO [resolve] Filtered out 9192495 UMIs as a result.
[2023-03-08 20:07:17,765]   DEBUG [resolve] Resulting molecule_table statistics:
[2023-03-08 20:07:17,765]   DEBUG [resolve] # Reads: 86
[2023-03-08 20:07:17,765]   DEBUG [resolve] # UMIs: 43
[2023-03-08 20:07:17,765]   DEBUG [resolve] # Cell BCs: 3
[2023-03-08 20:07:20,273]    INFO [resolve] Finished in 1383.8925580978394 s.
[2023-03-08 20:07:22,174]   DEBUG [align] Keyword arguments: {'gap_open_penalty': 20, 'gap_extend_penalty': 1, 'method': 'local', 'ref_filepath': '/home/zwf/Cassiopeia/Cassiopeia/data/PCT48.ref.fasta', 'ref': None, 'n_threads': 32}
[2023-03-08 20:07:22,174]    INFO [align] Starting...
Aligning sequences to reference: 100%|#####################################################################################################################################################################| 43/43 [00:06<00:00,  6.76it/s]
[2023-03-08 20:07:28,551]    INFO [align] Finished in 6.377103805541992 s.
[2023-03-08 20:07:28,552]   DEBUG [call_alleles] Keyword arguments: {'barcode_interval': (20, 34), 'cutsite_locations': [112, 166, 220], 'cutsite_width': 12, 'context': True, 'context_size': 5, 'ref_filepath': '/home/zwf/Cassiopeia/Cassiopeia/data/PCT48.ref.fasta', 'ref': None}
[2023-03-08 20:07:28,553]    INFO [call_alleles] Starting...
Parsing CIGAR strings into indels: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 10443.26it/s]
/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/pipeline.py:641: PreprocessWarning: Detected missing data in alleles. You might consider re-running align_sequences with a lower gap-open penalty, or using a separate alignment strategy.
  warnings.warn(
[2023-03-08 20:07:28,562]    INFO [call_alleles] Finished in 0.009550809860229492 s.
[2023-03-08 20:07:28,563]   DEBUG [error_correct_intbcs_to_whitelist] Keyword arguments: {'intbc_dist_thresh': 1, 'whitelist': ['ATGATTTAACTACT', 'CGATTGGTCACTTA', 'CGTGAGTCTCTGAT', 'GAACCCACAATTCC', 'GAGTATATACCCTT', 'GCGTTTAGAATATT', 'GCCTTCAATTCCAA', 'TAACCAAGCCTACA', 'TTTCGTCGCTCTTC', 'CGCTATGGGGGGAA', 'CGATATCTTCAAGC', 'TCAGTGGGGTATTG', 'ACAATGCGTGTGGC']}
[2023-03-08 20:07:28,563]    INFO [error_correct_intbcs_to_whitelist] Starting...
[2023-03-08 20:07:28,563]    INFO [error_correct_intbcs_to_whitelist] 1 intBCs detected.
Correcting intBCs to whitelist: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11214.72it/s]
[2023-03-08 20:07:28,565]    INFO [error_correct_intbcs_to_whitelist] Finished in 0.0015685558319091797 s.
[2023-03-08 20:07:28,565]   DEBUG [error_correct_umis] Keyword arguments: {'max_umi_distance': 2, 'allow_allele_conflicts': False, 'n_threads': 32}
[2023-03-08 20:07:28,565]    INFO [error_correct_umis] Starting...
Error-correcting UMIs: 0it [00:00, ?it/s]
[2023-03-08 20:07:28,569]    INFO [error_correct_umis] Finished in 0.0042383670806884766 s.
[2023-03-08 20:07:28,569]    INFO [main] Finished in 1479.447678565979 s.
Traceback (most recent call last):
  File "/home/pci/miniconda3/envs/py39/bin/cassiopeia-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 64, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/cassiopeia_preprocess.py", line 125, in main
    data = procedure(data, **pipeline_parameters[stage])
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 86, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 64, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/pipeline.py", line 786, in error_correct_umis
    alignment_df = pd.concat(alignment_dfs, sort=True)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by lamyankin** [comment]
Thank you for your reply and fix the bug, I have recloned the Cassiopeia and rerun the pipline from the step of  [resolve] with the input file /test.collapse.txt (9GB). However, I just got a 27KB output file /test.resolve.txt and met a error. Here is my .cfg file, and the process.

![image](https://user-images.githubusercontent.com/86952016/223714097-0055f5e2-5ff3-4677-8d56-6fc3b4084b24.png)
![image](https://user-images.githubusercontent.com/86952016/223714192-852f4c2f-0db6-42b3-8379-3567463e7316.png)

(py39) zwf 19:42:35 ~/Cassiopeia/Cassiopeia
$ cassiopeia-preprocess /home/zwf/Cassiopeia/Cassiopeia/data/preprocess.cfg
[2023-03-08 19:42:49,122]    INFO [main] Starting...
[2023-03-08 19:44:16,381]   DEBUG [resolve] Keyword arguments: {'min_avg_reads_per_umi': 2.0, 'min_umi_per_cell': 10, 'plot': True, 'output_directory': '/home/zwf/Cassiopeia'}
[2023-03-08 19:44:16,381]    INFO [resolve] Starting...
Resolving UMI sequences: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9192538/9192538 [19:54<00:00, 7695.42it/s]
[2023-03-08 20:05:18,606]    INFO [resolve] Filtered out 6148434 reads.
/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/shape_base.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ary = asanyarray(ary)
[2023-03-08 20:07:14,583]    INFO [resolve] Filtered out 136739 cells with too few UMIs or too few average number of reads per UMI.
[2023-03-08 20:07:17,432]    INFO [resolve] Filtered out 9192495 UMIs as a result.
[2023-03-08 20:07:17,765]   DEBUG [resolve] Resulting molecule_table statistics:
[2023-03-08 20:07:17,765]   DEBUG [resolve] # Reads: 86
[2023-03-08 20:07:17,765]   DEBUG [resolve] # UMIs: 43
[2023-03-08 20:07:17,765]   DEBUG [resolve] # Cell BCs: 3
[2023-03-08 20:07:20,273]    INFO [resolve] Finished in 1383.8925580978394 s.
[2023-03-08 20:07:22,174]   DEBUG [align] Keyword arguments: {'gap_open_penalty': 20, 'gap_extend_penalty': 1, 'method': 'local', 'ref_filepath': '/home/zwf/Cassiopeia/Cassiopeia/data/PCT48.ref.fasta', 'ref': None, 'n_threads': 32}
[2023-03-08 20:07:22,174]    INFO [align] Starting...
Aligning sequences to reference: 100%|#####################################################################################################################################################################| 43/43 [00:06<00:00,  6.76it/s]
[2023-03-08 20:07:28,551]    INFO [align] Finished in 6.377103805541992 s.
[2023-03-08 20:07:28,552]   DEBUG [call_alleles] Keyword arguments: {'barcode_interval': (20, 34), 'cutsite_locations': [112, 166, 220], 'cutsite_width': 12, 'context': True, 'context_size': 5, 'ref_filepath': '/home/zwf/Cassiopeia/Cassiopeia/data/PCT48.ref.fasta', 'ref': None}
[2023-03-08 20:07:28,553]    INFO [call_alleles] Starting...
Parsing CIGAR strings into indels: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 10443.26it/s]
/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/pipeline.py:641: PreprocessWarning: Detected missing data in alleles. You might consider re-running align_sequences with a lower gap-open penalty, or using a separate alignment strategy.
  warnings.warn(
[2023-03-08 20:07:28,562]    INFO [call_alleles] Finished in 0.009550809860229492 s.
[2023-03-08 20:07:28,563]   DEBUG [error_correct_intbcs_to_whitelist] Keyword arguments: {'intbc_dist_thresh': 1, 'whitelist': ['ATGATTTAACTACT', 'CGATTGGTCACTTA', 'CGTGAGTCTCTGAT', 'GAACCCACAATTCC', 'GAGTATATACCCTT', 'GCGTTTAGAATATT', 'GCCTTCAATTCCAA', 'TAACCAAGCCTACA', 'TTTCGTCGCTCTTC', 'CGCTATGGGGGGAA', 'CGATATCTTCAAGC', 'TCAGTGGGGTATTG', 'ACAATGCGTGTGGC']}
[2023-03-08 20:07:28,563]    INFO [error_correct_intbcs_to_whitelist] Starting...
[2023-03-08 20:07:28,563]    INFO [error_correct_intbcs_to_whitelist] 1 intBCs detected.
Correcting intBCs to whitelist: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11214.72it/s]
[2023-03-08 20:07:28,565]    INFO [error_correct_intbcs_to_whitelist] Finished in 0.0015685558319091797 s.
[2023-03-08 20:07:28,565]   DEBUG [error_correct_umis] Keyword arguments: {'max_umi_distance': 2, 'allow_allele_conflicts': False, 'n_threads': 32}
[2023-03-08 20:07:28,565]    INFO [error_correct_umis] Starting...
Error-correcting UMIs: 0it [00:00, ?it/s]
[2023-03-08 20:07:28,569]    INFO [error_correct_umis] Finished in 0.0042383670806884766 s.
[2023-03-08 20:07:28,569]    INFO [main] Finished in 1479.447678565979 s.
Traceback (most recent call last):
  File "/home/pci/miniconda3/envs/py39/bin/cassiopeia-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 64, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/cassiopeia_preprocess.py", line 125, in main
    data = procedure(data, **pipeline_parameters[stage])
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 86, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/utilities.py", line 64, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/cassiopeia/preprocess/pipeline.py", line 786, in error_correct_umis
    alignment_df = pd.concat(alignment_dfs, sort=True)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/pci/miniconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by lamyankin** [comment]
Thank you for your reply and fix the bug！
 I have recloned the Cassiopeia and rerun the pipline from the step of  [resolve] with the input file /test.collapse.txt . However, I met error in [error_correct_intbcs_to_whitelist] , possibly. The output file of  [error_correct_intbcs_to_whitelist] is nearly nothing in which just the rownames. I try turning off the [error_correct_intbcs_to_whitelist] and set None, it works. So it might get some problem in  [error_correct_intbcs_to_whitelist] .
Here is the error message: 
![屏幕截图 2023-03-09 154505](https://user-images.githubusercontent.com/86952016/223956179-25b21f51-e561-462f-af11-12f40b74b1f8.png)

**Comment by lamyankin** [comment]
It's my  fault!!
There should be a lot of intBCs, I just entered the 13 in github, I think that's the reason for the error.
sorry to disturb you.
